webAdmin.Web.Ui/Controllers/ClientesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using webAdmin.Domain.Core.Interfaces.Services;
using webAdmin.Domain.Entities;
using webAdmin.Web.Ui.ViewModels;

namespace webAdmin.Web.Ui.Controllers
{
    public class ClientesController : Controller
    {
        private readonly IClienteService _clienteService;
        private readonly IMapper _mapper;

        public ClientesController(IClienteService clienteService, IMapper mapper)
        {
            _clienteService = clienteService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var _clientes = _clienteService.GetAll();
            var _clienteViewModels = _mapper.Map<List<ClienteViewModel>>(_clientes);

            return View(_clienteViewModels);
        }

        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            var _clienteViewModel = _mapper.Map<ClienteViewModel>(_clienteService.GetById(id));

            if (id == 0)
                return View(new ClienteViewModel());
            else
                return View(_clienteViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("Id,Nome,Email,Celular")] ClienteViewModel clienteViewModel)
        {
            if (ModelState.IsValid)
            {
                var _cliente = _mapper.Map<Cliente>(clienteViewModel);

                if (clienteViewModel.Id == 0)
                    _clienteService.Add(_cliente);
                else
                    _clienteService.Update(_cliente);

                TempData["MensagemSucesso"] = "Cliente Cadastrado com sucesso";

                return RedirectToAction(nameof(Index));
            }

            return View(clienteViewModel);
        }

        public IActionResult Delete(int id)
        {
            var _cliente = _clienteService.GetById(id);
            
            _clienteService.Remove(_cliente);

            TempData["MensagemSucesso"] = "Cliente excluido com sucesso";

            return RedirectToAction(nameof(Index));
        }
    }
}

webAdmin.Web.Ui/Controllers/UsuariosController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using webAdmin.Domain.Core.Interfaces.Services;
using webAdmin.Domain.Entities;
using webAdmin.Domain.Services.Services;
using webAdmin.Web.Ui.Helper;
using webAdmin.Web.Ui.ViewModels;

namespace webAdmin.Web.Ui.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly IUsuarioService _usuarioService;
        private readonly IMapper _mapper;
        private readonly ISessao _sessao;

        public UsuariosController(IUsuarioService usuarioService, IMapper mapper, ISessao sessao)
        {
            _usuarioService = usuarioService;
            _mapper = mapper;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            var _usuarios = _usuarioService.GetAll();
            var _usuarioViewModel = _mapper.Map<List<UsuarioViewModel>>(_usuarios);

            return View(_usuarioViewModel);
        }

        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            var _usuarioViewModel = _mapper.Map<UsuarioViewModel>(_usuarioService.GetById(id));

            if (id == 0)
                return View(new UsuarioViewModel());
            else
                return View(_usuarioViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("Id, Nome, Login, Email, Perfil, Senha, DataCadastro, DataAtualizacao")] UsuarioViewModel usuarioViewModel)
        {
            if (ModelState.IsValid)
            {
                var _usuario = _mapper.Map<Usuario>(usuarioViewModel);

                if (usuarioViewModel.Id == 0)
                    _usuarioService.Add(_usuario);
                else
                    _usuarioService.Update(_usuario);

                TempData["MensagemSucesso"] = "Usuário Cadastrado com sucesso";

                return RedirectToAction(nameof(Index));
            }

            return View(usuarioViewModel);
        }

        public IActionResult Delete(int id)
        {
            var _usuario = _usuarioService.GetById(id);

            _usuarioService.Remove(_usuario);

            TempData["MensagemSucesso"] = "Usuário excluido com sucesso";

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit([Bind("Id, Nome, Login, Email, Perfil, Senha, DataCadastro, DataAtualizacao")] UsuarioViewModel usuarioViewModel)
        {
            if (ModelState.IsValid)
            {
                var usuarioLogado = _mapper.Map<UsuarioViewModel>(_sessao.BuscarSessaoDoUsuario());
                var _usuarioViewModel = _mapper.Map<UsuarioViewModel>(_usuarioService.GetById(usuarioLogado.Id));

                return View(_usuarioViewModel);
            }

            return View(usuarioViewModel);
        }
    }
}

webAdmin.Web.Ui/Views/Shared/Components/Menu/Default.cshtml
@model UsuarioViewModel

<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Olá, @Model.Nome</a>

<div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuPrincipal" data-bs-toggle="dropdown" aria-expanded="false">
        Menu Principal
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuPrincipal">
        <li class="dropdown-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
        </li>

        @if (Model.Perfil == webAdmin.Domain.Enums.PerfilEnum.Admin)
        {
            <li class="dropdown-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
            </li>
        }

        <li class="dropdown-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Edit">Alterar Senha</a>
        </li>

        <li class="dropdown-item">
            <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Sair">Sair</a>
        </li>
    </ul>
</div>

@*
<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Vendedores" asp-action="Index">Vendedores</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Pedidos" asp-action="Index">Pedidos</a>
        </li>

        @if (Model.Perfil == webAdmin.Web.Ui.Enums.PerfilEnum.Admin)
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a>
            </li>
        }

        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="AlterarSenha" asp-action="Index">Alterar Senha</a>
        </li>

        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Sair">Sair</a>
        </li>
    </ul>
</div>*@